### ISSUE TITLE
[User][model] Can't retrieve a user's events

### ISSUE THREAD

**Issue by heyapricot** [userman95/private-events#5]
I populated the database with a user and events both as an attendee and as an owner and I can't retrieve those. When I call either `my_user.events` or `my_user.attendances` I get nil

**Comment by rvvergara** [comment]
In relation to this, we better change the association name `events` into `attended_events` to remove confusion. Right now when we say `my_user.events`, the first thing that comes to mind is the `events` that were created by the user.

**Comment by rvvergara** [comment]
Awesome! This issue is resolved! :)
