### ISSUE TITLE
[User][show] The app should retrieve the user's events not the current user's events

### ISSUE THREAD

**Issue by heyapricot** [userman95/private-events#6]
So, on your user controller on the show action, you get the user by the id but you show events for the current user. `@upcoming_events` and `@previous_events` should separate the events for the user that you are displaying on the show page

**Comment by rvvergara** [comment]
I logged on as `user2` (with an ID=2). In this `current_user` 's page this is what I see:

![image](https://user-images.githubusercontent.com/6015315/58842673-ec127500-86a1-11e9-854d-55834b1c5421.png)

Now without logging off (still logged on as `user2`) I visit `user1` 's page (`/users/1`), yet I see the same things in that page:

![image](https://user-images.githubusercontent.com/6015315/58842702-08161680-86a2-11e9-9290-20bbd76dd9fc.png)

`user1` in this case had created an event but it isn't showing. And the text i am seeing as `user2` is still "Your Events" when those that I should see are `user1` 's events.

**Comment by efrapp** [comment]
Ok @rvvergara we got the point. We're going to fix that.
